### ISSUE TITLE
Goto: file

### ISSUE THREAD

**Issue by blakjakau** [blakjakau/dev.jakbox.code#1]
Add filename lookup to the omnibox for "Goto". 
This could be just all active/open files? Or perhaps a background task could iterate the workspace folders and create an index?

**Comment by Wrongtown** [comment]
+1 for including files in any folders you've added, absolutely love this in Sublime Text.

**Comment by blakjakau** [comment]
Needs a little work. When there's multiple locked folders (e.g. when the app is first opened and permission have not been refreshed), if the index is generating AND subsequent folders are unlocked, the newly unlocked folders don't get index. Needs a queued / delayed repeat call to generateIndex if it's already running when the file is triggered.
