### ISSUE TITLE
Django is at the end of an otherwise alphabetically-sorted list

### ISSUE THREAD

**Issue by Wrongtown** [blakjakau/dev.jakbox.code#4]
In the context of the other items in the list I'm guessing this is not intentional.

![2022-01-17_185949-django-sort-order](https://user-images.githubusercontent.com/16337876/149759153-6f066ca0-b981-4e3b-8e4d-1511df85e8aa.png)

**Comment by Wrongtown** [comment]
Note that this ordering is replicated in other instances, for example if you left-click the mode indicator at bottom-right of the window next to the theme indicator.

I've raised PR #5 with the intent of resolving this.

**Comment by Wrongtown** [comment]
@blakjakau looks like #5 is merged but not deployed to https://code.jakbox.dev/ as yet?

**Comment by blakjakau** [comment]
> @blakjakau looks like #5 is merged but not deployed to https://code.jakbox.dev/ as yet?
> 
> Either that or the fix in #5 was not suitable.

@Wrongtown my bad, I use this editor 8-10 hours a day, but I only rarely update the deployed version. This change has been deployed to the hosted copy.
